// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.phonecall.app.phone_call_app.platform

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PlatformApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class CallLogFilter(val raw: Int) {
  ALL(0),
  MISSED(1);

  companion object {
    fun ofRaw(raw: Int): CallLogFilter? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CallType(val raw: Int) {
  UNKNOWN(0),
  INCOMING(1),
  OUTGOING(2),
  MISSED(3),
  REJECTED(4),
  BLOCKED(5),
  VOICEMAIL(6);

  companion object {
    fun ofRaw(raw: Int): CallType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CallStatus(val raw: Int) {
  IDLE(0),
  RINGING(1),
  DIALING(2),
  ACTIVE(3),
  HELD(4),
  DISCONNECTED(5);

  companion object {
    fun ofRaw(raw: Int): CallStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class AudioRoute(val raw: Int) {
  EARPIECE(0),
  SPEAKER(1),
  BLUETOOTH(2),
  WIRED_HEADSET(3);

  companion object {
    fun ofRaw(raw: Int): AudioRoute? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformApiConfiguration (
  val marker: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformApiConfiguration {
      val marker = pigeonVar_list[0] as String?
      return PlatformApiConfiguration(marker)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      marker,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PlatformApiConfiguration) {
      return false
    }
    if (this === other) {
      return true
    }
    return PlatformApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PermissionState (
  val contactsGranted: Boolean? = null,
  val writeContactsGranted: Boolean? = null,
  val callLogGranted: Boolean? = null,
  val phoneGranted: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PermissionState {
      val contactsGranted = pigeonVar_list[0] as Boolean?
      val writeContactsGranted = pigeonVar_list[1] as Boolean?
      val callLogGranted = pigeonVar_list[2] as Boolean?
      val phoneGranted = pigeonVar_list[3] as Boolean?
      return PermissionState(contactsGranted, writeContactsGranted, callLogGranted, phoneGranted)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contactsGranted,
      writeContactsGranted,
      callLogGranted,
      phoneGranted,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PermissionState) {
      return false
    }
    if (this === other) {
      return true
    }
    return PlatformApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SimAccount (
  val id: String? = null,
  val label: String? = null,
  val address: String? = null,
  val isDefault: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SimAccount {
      val id = pigeonVar_list[0] as String?
      val label = pigeonVar_list[1] as String?
      val address = pigeonVar_list[2] as String?
      val isDefault = pigeonVar_list[3] as Boolean?
      return SimAccount(id, label, address, isDefault)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      label,
      address,
      isDefault,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SimAccount) {
      return false
    }
    if (this === other) {
      return true
    }
    return PlatformApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PhoneNumberEntry (
  val label: String? = null,
  val number: String? = null,
  val normalizedNumber: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PhoneNumberEntry {
      val label = pigeonVar_list[0] as String?
      val number = pigeonVar_list[1] as String?
      val normalizedNumber = pigeonVar_list[2] as String?
      return PhoneNumberEntry(label, number, normalizedNumber)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      label,
      number,
      normalizedNumber,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PhoneNumberEntry) {
      return false
    }
    if (this === other) {
      return true
    }
    return PlatformApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class EmailEntry (
  val label: String? = null,
  val address: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EmailEntry {
      val label = pigeonVar_list[0] as String?
      val address = pigeonVar_list[1] as String?
      return EmailEntry(label, address)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      label,
      address,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is EmailEntry) {
      return false
    }
    if (this === other) {
      return true
    }
    return PlatformApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ContactSummary (
  val id: String? = null,
  val lookupKey: String? = null,
  val displayName: String? = null,
  val photoUri: String? = null,
  val isStarred: Boolean? = null,
  val primaryNumber: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ContactSummary {
      val id = pigeonVar_list[0] as String?
      val lookupKey = pigeonVar_list[1] as String?
      val displayName = pigeonVar_list[2] as String?
      val photoUri = pigeonVar_list[3] as String?
      val isStarred = pigeonVar_list[4] as Boolean?
      val primaryNumber = pigeonVar_list[5] as String?
      return ContactSummary(id, lookupKey, displayName, photoUri, isStarred, primaryNumber)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      lookupKey,
      displayName,
      photoUri,
      isStarred,
      primaryNumber,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ContactSummary) {
      return false
    }
    if (this === other) {
      return true
    }
    return PlatformApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ContactDetail (
  val id: String? = null,
  val lookupKey: String? = null,
  val givenName: String? = null,
  val familyName: String? = null,
  val displayName: String? = null,
  val company: String? = null,
  val photoUri: String? = null,
  val isStarred: Boolean? = null,
  val phoneNumbers: List<PhoneNumberEntry?>? = null,
  val emailAddresses: List<EmailEntry?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ContactDetail {
      val id = pigeonVar_list[0] as String?
      val lookupKey = pigeonVar_list[1] as String?
      val givenName = pigeonVar_list[2] as String?
      val familyName = pigeonVar_list[3] as String?
      val displayName = pigeonVar_list[4] as String?
      val company = pigeonVar_list[5] as String?
      val photoUri = pigeonVar_list[6] as String?
      val isStarred = pigeonVar_list[7] as Boolean?
      val phoneNumbers = pigeonVar_list[8] as List<PhoneNumberEntry?>?
      val emailAddresses = pigeonVar_list[9] as List<EmailEntry?>?
      return ContactDetail(id, lookupKey, givenName, familyName, displayName, company, photoUri, isStarred, phoneNumbers, emailAddresses)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      lookupKey,
      givenName,
      familyName,
      displayName,
      company,
      photoUri,
      isStarred,
      phoneNumbers,
      emailAddresses,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ContactDetail) {
      return false
    }
    if (this === other) {
      return true
    }
    return PlatformApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class EditableContact (
  val contactId: String? = null,
  val givenName: String? = null,
  val familyName: String? = null,
  val company: String? = null,
  val isStarred: Boolean? = null,
  val phoneNumbers: List<PhoneNumberEntry?>? = null,
  val emailAddresses: List<EmailEntry?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EditableContact {
      val contactId = pigeonVar_list[0] as String?
      val givenName = pigeonVar_list[1] as String?
      val familyName = pigeonVar_list[2] as String?
      val company = pigeonVar_list[3] as String?
      val isStarred = pigeonVar_list[4] as Boolean?
      val phoneNumbers = pigeonVar_list[5] as List<PhoneNumberEntry?>?
      val emailAddresses = pigeonVar_list[6] as List<EmailEntry?>?
      return EditableContact(contactId, givenName, familyName, company, isStarred, phoneNumbers, emailAddresses)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contactId,
      givenName,
      familyName,
      company,
      isStarred,
      phoneNumbers,
      emailAddresses,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is EditableContact) {
      return false
    }
    if (this === other) {
      return true
    }
    return PlatformApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RecentCall (
  val id: String? = null,
  val number: String? = null,
  val displayName: String? = null,
  val photoUri: String? = null,
  val contactId: String? = null,
  val timestampMillis: Long? = null,
  val durationSeconds: Long? = null,
  val type: CallType? = null,
  val accountId: String? = null,
  val occurrences: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RecentCall {
      val id = pigeonVar_list[0] as String?
      val number = pigeonVar_list[1] as String?
      val displayName = pigeonVar_list[2] as String?
      val photoUri = pigeonVar_list[3] as String?
      val contactId = pigeonVar_list[4] as String?
      val timestampMillis = pigeonVar_list[5] as Long?
      val durationSeconds = pigeonVar_list[6] as Long?
      val type = pigeonVar_list[7] as CallType?
      val accountId = pigeonVar_list[8] as String?
      val occurrences = pigeonVar_list[9] as Long?
      return RecentCall(id, number, displayName, photoUri, contactId, timestampMillis, durationSeconds, type, accountId, occurrences)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      number,
      displayName,
      photoUri,
      contactId,
      timestampMillis,
      durationSeconds,
      type,
      accountId,
      occurrences,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RecentCall) {
      return false
    }
    if (this === other) {
      return true
    }
    return PlatformApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CallSessionState (
  val callId: String? = null,
  val number: String? = null,
  val displayName: String? = null,
  val photoUri: String? = null,
  val status: CallStatus? = null,
  val isMuted: Boolean? = null,
  val canMute: Boolean? = null,
  val canHold: Boolean? = null,
  val isOnHold: Boolean? = null,
  val canMerge: Boolean? = null,
  val canSwap: Boolean? = null,
  val canAnswer: Boolean? = null,
  val canReject: Boolean? = null,
  val canDisconnect: Boolean? = null,
  val canDtmf: Boolean? = null,
  val isConference: Boolean? = null,
  val shouldShowFullScreen: Boolean? = null,
  val connectTimeMillis: Long? = null,
  val selectedAudioRoute: AudioRoute? = null,
  val availableAudioRoutes: List<AudioRoute?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CallSessionState {
      val callId = pigeonVar_list[0] as String?
      val number = pigeonVar_list[1] as String?
      val displayName = pigeonVar_list[2] as String?
      val photoUri = pigeonVar_list[3] as String?
      val status = pigeonVar_list[4] as CallStatus?
      val isMuted = pigeonVar_list[5] as Boolean?
      val canMute = pigeonVar_list[6] as Boolean?
      val canHold = pigeonVar_list[7] as Boolean?
      val isOnHold = pigeonVar_list[8] as Boolean?
      val canMerge = pigeonVar_list[9] as Boolean?
      val canSwap = pigeonVar_list[10] as Boolean?
      val canAnswer = pigeonVar_list[11] as Boolean?
      val canReject = pigeonVar_list[12] as Boolean?
      val canDisconnect = pigeonVar_list[13] as Boolean?
      val canDtmf = pigeonVar_list[14] as Boolean?
      val isConference = pigeonVar_list[15] as Boolean?
      val shouldShowFullScreen = pigeonVar_list[16] as Boolean?
      val connectTimeMillis = pigeonVar_list[17] as Long?
      val selectedAudioRoute = pigeonVar_list[18] as AudioRoute?
      val availableAudioRoutes = pigeonVar_list[19] as List<AudioRoute?>?
      return CallSessionState(callId, number, displayName, photoUri, status, isMuted, canMute, canHold, isOnHold, canMerge, canSwap, canAnswer, canReject, canDisconnect, canDtmf, isConference, shouldShowFullScreen, connectTimeMillis, selectedAudioRoute, availableAudioRoutes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      callId,
      number,
      displayName,
      photoUri,
      status,
      isMuted,
      canMute,
      canHold,
      isOnHold,
      canMerge,
      canSwap,
      canAnswer,
      canReject,
      canDisconnect,
      canDtmf,
      isConference,
      shouldShowFullScreen,
      connectTimeMillis,
      selectedAudioRoute,
      availableAudioRoutes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CallSessionState) {
      return false
    }
    if (this === other) {
      return true
    }
    return PlatformApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class PlatformApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CallLogFilter.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CallType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CallStatus.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AudioRoute.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformApiConfiguration.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PermissionState.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SimAccount.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PhoneNumberEntry.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EmailEntry.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ContactSummary.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ContactDetail.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EditableContact.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RecentCall.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CallSessionState.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CallLogFilter -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is CallType -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is CallStatus -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is AudioRoute -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformApiConfiguration -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is PermissionState -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is SimAccount -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is PhoneNumberEntry -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is EmailEntry -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is ContactSummary -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is ContactDetail -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is EditableContact -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is RecentCall -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is CallSessionState -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface DialerPlatformApi {
  fun getPermissionState(): PermissionState
  fun requestCorePermissions(): Boolean
  fun isDefaultDialer(): Boolean
  fun requestDefaultDialerRole(): Boolean
  fun getCallCapableAccounts(): List<SimAccount?>
  fun placeCall(number: String, accountId: String?)
  fun getCurrentCallState(): CallSessionState?
  fun answerCall()
  fun rejectCall()
  fun disconnectCall()
  fun setMuted(muted: Boolean)
  fun setAudioRoute(route: AudioRoute)
  fun setHold(onHold: Boolean)
  fun playDtmfTone(digit: String)
  fun stopDtmfTone()
  fun swapCalls()
  fun mergeCalls()

  companion object {
    /** The codec used by DialerPlatformApi. */
    val codec: MessageCodec<Any?> by lazy {
      PlatformApiPigeonCodec()
    }
    /** Sets up an instance of `DialerPlatformApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DialerPlatformApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.DialerPlatformApi.getPermissionState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getPermissionState())
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.DialerPlatformApi.requestCorePermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.requestCorePermissions())
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.DialerPlatformApi.isDefaultDialer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isDefaultDialer())
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.DialerPlatformApi.requestDefaultDialerRole$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.requestDefaultDialerRole())
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.DialerPlatformApi.getCallCapableAccounts$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCallCapableAccounts())
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.DialerPlatformApi.placeCall$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val numberArg = args[0] as String
            val accountIdArg = args[1] as String?
            val wrapped: List<Any?> = try {
              api.placeCall(numberArg, accountIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.DialerPlatformApi.getCurrentCallState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCurrentCallState())
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.DialerPlatformApi.answerCall$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.answerCall()
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.DialerPlatformApi.rejectCall$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.rejectCall()
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.DialerPlatformApi.disconnectCall$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.disconnectCall()
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.DialerPlatformApi.setMuted$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val mutedArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setMuted(mutedArg)
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.DialerPlatformApi.setAudioRoute$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val routeArg = args[0] as AudioRoute
            val wrapped: List<Any?> = try {
              api.setAudioRoute(routeArg)
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.DialerPlatformApi.setHold$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val onHoldArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setHold(onHoldArg)
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.DialerPlatformApi.playDtmfTone$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val digitArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.playDtmfTone(digitArg)
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.DialerPlatformApi.stopDtmfTone$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopDtmfTone()
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.DialerPlatformApi.swapCalls$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.swapCalls()
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.DialerPlatformApi.mergeCalls$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.mergeCalls()
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ContactsPlatformApi {
  fun searchContacts(query: String): List<ContactSummary?>
  fun getContact(id: String): ContactDetail?
  fun saveContact(contact: EditableContact): ContactDetail
  fun deleteContact(id: String)
  fun toggleFavorite(id: String, isStarred: Boolean)

  companion object {
    /** The codec used by ContactsPlatformApi. */
    val codec: MessageCodec<Any?> by lazy {
      PlatformApiPigeonCodec()
    }
    /** Sets up an instance of `ContactsPlatformApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ContactsPlatformApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.ContactsPlatformApi.searchContacts$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val queryArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.searchContacts(queryArg))
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.ContactsPlatformApi.getContact$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.getContact(idArg))
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.ContactsPlatformApi.saveContact$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val contactArg = args[0] as EditableContact
            val wrapped: List<Any?> = try {
              listOf(api.saveContact(contactArg))
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.ContactsPlatformApi.deleteContact$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.deleteContact(idArg)
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.ContactsPlatformApi.toggleFavorite$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val isStarredArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.toggleFavorite(idArg, isStarredArg)
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface RecentsPlatformApi {
  fun getRecentCalls(filter: CallLogFilter): List<RecentCall?>
  fun getCallDetails(id: String): RecentCall?

  companion object {
    /** The codec used by RecentsPlatformApi. */
    val codec: MessageCodec<Any?> by lazy {
      PlatformApiPigeonCodec()
    }
    /** Sets up an instance of `RecentsPlatformApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: RecentsPlatformApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.RecentsPlatformApi.getRecentCalls$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filterArg = args[0] as CallLogFilter
            val wrapped: List<Any?> = try {
              listOf(api.getRecentCalls(filterArg))
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.phone_call_app.RecentsPlatformApi.getCallDetails$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.getCallDetails(idArg))
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class CallStateFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by CallStateFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      PlatformApiPigeonCodec()
    }
  }
  fun onCallStateChanged(stateArg: CallSessionState, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.phone_call_app.CallStateFlutterApi.onCallStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PlatformApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
